dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install pycodestyle
  - pip install flake8
before_script:
  - "pycodestyle --max-line-length=140 --ignore=D100,D103 ./"
  - "flake8 --max-line-length=140"